### ISSUE TITLE
tlg2001.tlg043.opp-grc1 should be tlg2001.tlg043.opp-lat1

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1140] opened 2017-03-28 19:24 UTC
This work by Themistius is entirely in Latin. Should I do a pull request deleting and renaming the file as well as updating the bibliographic and other info @sonofmun? Thanks!

**Comment by sonofmun** [comment] 2017-06-15 12:01
@AlisonBabeu Sorry to reply to this issue so late. But yes, if you could make all the necessary changes, that would be great.
Just a note here: since this is a translation, it should be marked as such both in the XML file and in the metadata file.

**Comment by brittanyhardy** [comment] 2017-06-21 17:40
![screen shot 2017-06-21 at 1 35 26 pm](https://user-images.githubusercontent.com/29205107/27398087-a611703a-5686-11e7-8818-4fabf513e922.png)
I tried sending these corrected files to Travis, and I received this result after completing the test. I've never opened any of these files that are shown as failing, and these same files were listed when I tried submitting issue 155 (same for when @Pria20 tried submitting several of her files). Any thoughts as to why this is happening? @lmuellner

**Comment by lmuellner** [comment] 2017-06-21 18:50
Hi Brittany, I’m not sure what is going on — I’ll check out these files and see if I can figure out what’s going on, more soon. Best, Lenny

**Comment by lmuellner** [comment] 2017-06-21 19:19
Hi  Brittany, 

I can't find these in my repo--but it may be out of date.  Just to be clear, when you run Hooktest on Travis it tests *all* the files in thé DB. So if someone undesirable made a mistake, jt will show up in the report. It'd be worthwhile to check out.  But first you need to see if you have the files that cause the problems. Let me know! 

Best, Lenny

**Comment by Pria20** [comment] 2017-06-21 19:34
We do have the files in our repositories but prior to receiving this message, neither Brittany nor I had opened these 3 files. We were working on separate issues and both of ours got kicked back from travis with the same message

**Comment by sonofmun** [comment] 2017-06-21 20:13
The problem is that we added a test and now files that were not failing are now failing. Or were. I fixed them so if you pull from the master branch on the a Open Greek and Latin repo, the problem should be fixed.

**Comment by Pria20** [comment] 2017-06-21 20:45
I did a git pull and tried to push issue 346 again. The test failed travis and sent back the same message about the 3 files

**Comment by AlisonBabeu** [comment] 2017-09-18 14:23
It looks like this file is correct and complete now, so can I close this issue @sonofmun?

**Comment by sonofmun** [comment] 2017-09-18 14:44
Yes, please do.

**Closed** 2017-09-18 15:15 UTC
