### ISSUE TITLE
Go through Claudius Ptolemaeus, Syntaxis mathematica and add missing content

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/First1KGreek#1408] opened 2017-06-06 10:13 UTC
tlg0363.tlg001.1st1K-grc1.xml
This file passes but I don't know how useful it is. The tables are not well represented. The diagrams are completely missing. At points where the page layout is landscape instead of portrait, all of the content is missing.

**Comment by annettegessner** [comment] 2017-06-14 13:57
The main problem of this file a re the missing figures and (lots of pages with) tables.
I added "placeholders" for the figures and tables until page 333. If this kind of mark up is accepted (see #251), this would have to be done for the rest of the file too.

**Comment by annettegessner** [comment] 2017-08-31 13:18
@lmuellner: This might be an easy (albeit tedious) to fix task to assign to somebody.

**Comment by lcerrato** [comment] 2018-06-08 16:59
Hi @jdeen33 
See my recent comment on #1546. Adding the place is fine: Oxygen offers a preloaded list of common terms, but as long as you are consistent, it's ok. 
Not mandatory, however, as it can become laborious.
I would suggest seeing if there is a predominant usage and tagging exceptions first. For instance, if most figures are inline, just add the attribute for those in the margin and then globally add the attribute for the ones that are inline.

**Comment by lmuellner** [comment] 2018-06-08 17:59
Hi Julia, Annette says that she put in placeholders for the figures and tables until page 333. What do they look like? One thing you could do is to continue doing what she did where she left off. Let me know what you find! Best, Lenny

**Comment by lmuellner** [comment] 2018-06-08 18:01
Actually, check this out: https://github.com/OpenGreekAndLatin/First1KGreek/issues/251

**Comment by jdeen33** [comment] 2018-06-09 22:37
thank you @lmuellner and @lcerrato i will check this out !

**Comment by lcerrato** [comment] 2018-06-11 16:06
Hi @jdeen33 
The issue is that EpiDoc does not permit tables, but of course TEI does. So the short workaround that was discussed is just to link to the image for a complex table:
`<figure rend="table"><graphic url="https://archive.org/stream/claudiiptolemae00ptolgoog#page/n91/mode/1up"/></figure>`
versus 

```xml
<list rend="table">
    <item>
        <list rend="row"> <item><label><num>α΄</num></label></item><item>μακρὸς</item><item>πλατὺς</item><item>ὑψηλὸς</item> <item>μέγας</item> </list> 
        <list rend="row"> <item><label><num>β΄</num></label></item><item>μακρὸς</item><item>πλατὺς</item><item>σύμμετρος</item> </list>
        <list rend="row"> <item><label><num>γ΄</num></label></item><item>μακρὸς</item><item>πλατὺς</item> <item>ταπεινὸς</item> </list>
    </item> 
</list>
```

**Comment by lcerrato** [comment] 2018-06-11 16:12
Note that both solutions are used in tlg0057.tlg059.1st1k-grc1.xml:
`OGL:First1KGreek/data/tlg0057/tlg059/tlg0057.tlg059.1st1K-grc1.xml`
 ```
     <figure>
     <graphic url="https://babel.hathitrust.org/cgi/pt?id=hvd.hxpp8p;view=2up;seq=542"/>
                            <figDesc>
                                   <list rend="table">
                                          <item>
                                                 <list rend="row">
                                                       <item><label><num>α΄</num></label></item>
                                                       <item>ταχὺς</item>
                                                        <item>βραδὺς</item>
                                                   </list>
                                  ...
                                           </item>
                                     </list>
                                </figDesc>
                        </figure>

**Comment by jdeen33** [comment] 2018-06-11 17:51
@lcerrato thank you-- this is super helpful!

-Julia

**Comment by lcerrato** [comment] 2018-06-11 18:02
@jdeen33 
Just keep pinging me! Thank you for looking at this.
--Lisa

**Comment by jdeen33** [comment] 2018-06-14 13:43
<img width="1398" alt="screenshot 2018-06-14 09 42 53" src="https://user-images.githubusercontent.com/39914695/41415783-615d1e4e-6fb7-11e8-83f7-810951b8c4bc.png">



@lcerrato this is an example of how i've been formatting the tables--what do you think?

**Comment by lcerrato** [comment] 2018-06-14 18:12
Hi @jdeen33 
I think you want to enclose the entire table/list in the figure tag and a `<figDesc>` tag if I am reading the example from tlg0057.tlg059.1st1K-grc1.xml above correctly. Please double check the file itself. I may have mistyped something.

So the basic nesting looks like
`<figure>` no attribute
`<graphic>` with the url (note this encloses nothing but is self contained)
`<figDesc>` no attribute
`<list rend="table">`
`<item>`
`<list rend="row">` multiple times 
`<item>` (first item has a `<label>` if it is a header
`</item>` close the item(s)
`</list>` close the row(s)
`</item>` close the enclosing item
`</list>`close the `<list rend="table">`
`</figDesc>`
`</figure>` now close the entire figure

--Lisa

**Closed** 2019-03-11 16:29 UTC
